mavros_node:
  ros__parameters:
    fcu_url: "udp://:14550@"
    gcs_url: ""
    tgt_system: 1
    tgt_component: 1

###################
### plugin params ###
###################

# actuator_control None
# adsb None

# altitude:
#   ros__parameters: 
#   frame_id: map

# cam_imu_sync None
# camera None

# cmd:
#   ros__parameters:
#     use_comp_id_system_control: true
#     command_ack_timeout: 5000ms

# companion_process_status None
# debug_value None
# distance_sensor None
# esc_status None
# esc_telemetry None
# fake_gps None
# ftp None

# geofence:
#   ros__parameters:
#     pull_after_gcs: true
#     use_mission_item_int: true

# global_position:
#   ros__parameters:
#     frame_id: map
#     child_frame_id: base_link
#     rot_covariance: 99999.0
#     gps_uere: 1.0
#     use_relative_alt: true
#     tf:
#       send: false
#       frame_id: map
#       global_frame_id: earth
#       child_frame_id: base_link

# gps_input None
# gps_rtk None
# gps_status None
# hil None
# home_position None

# imu:
#   ros__parameters:
#     frame_id: true
#     linear_acceleration_stdev: 0.0003
#     angular_velocity_stdev: 0.02 * (M_PI / 180.0)
#     orientation_stdev: 1.0
#     magnetic_stdev: 0.0

# landing_target None
# gps_rtk None

# local_position:
#   ros__parameters:
#     frame_id: map
#     tf:
#       send: false
#       frame_id: map
#       child_frame_id: base_link

# log_transfer None
# mag_calibration_status None
# manual_control None
# mocap_pose_estimate None
# mount_control None
# nav_controller_output None
# obstacle_distance None

# odometry:
#   ros__parameters:
#     fcu:
#       odom_parent_id_des: map
#       odom_child_id_des: map

# onboard_computer_status None
# param None
# play_tune None

# px:
#   ros__parameters:
#     frame_id: px4flow
#     ranger_fov: 0.119428926
#     ranger_min_range: 0.3
#     ranger_max_range: 5.0

# rallypoint:
#   ros__parameters:
#     pull_after_gcs: true
#     use_mission_item_int: true

# rangefinder None
# rc_io None
# setpoint_accel None

# setpoint_attitude:
#     ros__parameters:
#       reverse_thrust: false
#       use_quaternion: false

# setpoint_position:
#     ros__parameters:
#       mav_frame: LOCAL_NED

# setpoint_raw:
#     ros__parameters:
#       thrust_scaling: NAN

# setpoint_trajectory:
#     ros__parameters:
#       frame_id: map
#       mav_frame: LOCAL_NED

# setpoint_velocity:
#     ros__parameters:
#       mav_frame: LOCAL_NED

# sys_status:
#   ros__parameters:
#     conn_timeout: 10.0
#     min_voltage: 10.0
#     disable_diag: false
#     heartbeat_mav_type: ONBOARD_CONTROLLER
#     heartbeat_rate: 1.0

# sys_time:
#   ros__parameters:
#     time_ref_source: fcu
#     timesync_mode: MAVLINK
#     system_time_rate: 0.0
#     timesync_rate: 0.0
#     timesync_alpha_initial: 0.05
#     timesync_beta_initial: 0.05
#     timesync_alpha_final: 0.003
#     timesync_beta_final: 0.003
#     convergence_window: 500
#     max_rtt_sample: 10
#     max_deviation_sample: 10
#     max_consecutive_high_rtt: 10
#     max_consecutive_high_deviation: 10

# terrain None
# tdr_radio None
# trajectory None
# tunnel None
# vfr_hud None

# vibration:
#   ros__parameters:
#     frame_id: base_link

# vision_pose:
#   ros__parameters:
#     tf/listen: false
#     tf/frame_id: map
#     tf/child_frame_id: vision_estimate
#     tf/rate_limit: 10.0

# vision_speed None

# waypoint:
#   ros__parameters:
#     pull_after_gcs: true
#     use_mission_item_int: true
#     enable_partial_push: 2

# wheel_odomotry
#   ros__parameters:
#     send_raw: false
#     count: 2
#     use_rpm: false
#     send_twist: false
#     frame_id: odom
#     child_frame_id: base_link
#     vel_error: 0.1
#     tf:
#       frame_id: odom
#       child_frame_id: base_link
#       send: false
#     wheel1:
#       x: 0.0
#       y: 0.0
#       radius: 0.05

# wind_estimation None






